# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [6]:
### [your code here]
# Printing the version of NumPy installed
print(np.__version__)
print("------------------------------------------")
# Printing the configuration details of NumPy
print(np.show_config())


2.0.2
------------------------------------------
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-vclkdodh/cp39-win_amd64/build/venv/Lib/site-packa

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [17]:
### [your code here]
a = np.random.random((2,3,5))
a = np.random.rand(2,3,5)
a = np.random.randint(0,10,(2, 3, 5))
a = np.random.choice([3, 5, 7, 9], size=(2, 3, 5))



### 4. Print a.


In [18]:
### [your code here]
print(a)

[[[3 7 7 5 9]
  [5 5 5 7 5]
  [7 9 9 3 5]]

 [[3 5 3 9 7]
  [7 3 9 9 5]
  [7 3 5 7 5]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [35]:
### [your code here]
# b = np.ones((5, 3, 2))
b = np.ones((5, 2, 3))


### 6. Print b.


In [36]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [37]:
### [your code here]
a.size == b.size


True


### 8. Are you able to add a and b? Why or why not?


In [38]:
### [your code here]

a + b
# ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [59]:
### [your code here]
# axes=(2,3,5)
# permutation


c = np.transpose(b, axes=(1,2,0))
# (5, 2, 3) 
# -> 5: old position 0 should go into the last position 
# -> 2: old position 1 should go into the first position
# -> 3: old position 2 should go into the middle position
a.shape, b.shape, c.shape


((2, 3, 5), (5, 2, 3), (2, 3, 5))


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [62]:
### [your code here]
d = a + c
# it works now because the shapes of the two variables are identical
a.shape == c.shape

True


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
### [your code here]
print(a)
print("----------------------------")
print(d)
# every entry in d was increased by 1 because the added matrix c contained a 1 in each cell

[[[3 7 7 5 9]
  [5 5 5 7 5]
  [7 9 9 3 5]]

 [[3 5 3 9 7]
  [7 3 9 9 5]
  [7 3 5 7 5]]]
----------------------------
[[[ 4.  8.  8.  6. 10.]
  [ 6.  6.  6.  8.  6.]
  [ 8. 10. 10.  4.  6.]]

 [[ 4.  6.  4. 10.  8.]
  [ 8.  4. 10. 10.  6.]
  [ 8.  4.  6.  8.  6.]]]



### 12. Multiply a and c. Assign the result to e.


In [66]:
### [your code here]
e = a * c
e

array([[[3., 7., 7., 5., 9.],
        [5., 5., 5., 7., 5.],
        [7., 9., 9., 3., 5.]],

       [[3., 5., 3., 9., 7.],
        [7., 3., 9., 9., 5.],
        [7., 3., 5., 7., 5.]]])



### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]
# c is filled with floatingpoint ones so a multiplication only transforms the datatype from int to float




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [90]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [91]:
### [your code here]
f = np.empty((2,3,5))
f

array([[[  0.,  75.,  75.,  25., 100.],
        [ 25.,  25.,  25.,  75.,  25.],
        [ 75., 100., 100.,   0.,  25.]],

       [[  0.,  25.,   0., 100.,  75.],
        [ 75.,   0., 100., 100.,  25.],
        [ 75.,   0.,  25.,  75.,  25.]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [92]:
### [your code here]
# For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
f[(d > d_min) & (d < d_mean)] = 25
# If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
f[(d > d_mean) & (d < d_max)] = 75
# If a value equals to d_mean, assign 50 to the corresponding value in f.
f[(d == d_mean)] = 50
# Assign 0 to the corresponding value(s) in f for d_min in d.
f[(d == d_min)] = 0
# Assign 100 to the corresponding value(s) in f for d_max in d.
f[(d == d_max)] = 100
print(f)

[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [95]:
### [your code here]
## test 
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
f = np.empty((2,3,5))
# For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
f[(d > d_min) & (d < d_mean)] = 25
# If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
f[(d > d_mean) & (d < d_max)] = 75
# If a value equals to d_mean, assign 50 to the corresponding value in f.
f[(d == d_mean)] = 50
# Assign 0 to the corresponding value(s) in f for d_min in d.
f[(d == d_min)] = 0
# Assign 100 to the corresponding value(s) in f for d_max in d.
f[(d == d_max)] = 100

# print(f)


f_test = np.array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

f == f_test

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
### [your code here]
f = np.empty((2,3,5), dtype="str")
# For each value in d, if it's larger than d_min but smaller than d_mean, assign "B" to the corresponding value in f.
f[(d > d_min) & (d < d_mean)] = "B"
# If a value in d is larger than d_mean but smaller than d_max, assign D to the corresponding value in f.
f[(d > d_mean) & (d < d_max)] = "D"
# If a value equals to d_mean, assign C to the corresponding value in f.
f[(d == d_mean)] = "C"
# Assign A to the corresponding value(s) in f for d_min in d.
f[(d == d_min)] = "A"
# Assign E to the corresponding value(s) in f for d_max in d.
f[(d == d_max)] = "E"

f_test_2 = np.array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])

print(f == f_test_2)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
